shinyUI(navbarPage('Sistema de Telas - Full Body',
                   theme = shinytheme('flatly'),
                   #### Ingresos ----
                   tabPanel('Ingresos',
                            shinyjs::useShinyjs(),
                            useShinyalert(),
                            tags$style(type='text/css', ".selectize-input {height: 42px; }"),
                            tabPanel('Nuevo',
                                     wellPanel(style = wellPanel.style,
                                               fluidRow(column(2,textInput('incoming.id1',
                                                                           'ID 1')),
                                                        column(2,textInput('incoming.id2',
                                                                           'ID 2')),
                                                        column(2, uiOutput('incoming.date')),
                                                        column(2, uiOutput('incoming.provider')),
                                                        column(2, uiOutput('incoming.fabric')),
                                                        column(2, uiOutput('incoming.kg'))
                                               ),
                                               fluidRow(column(2, uiOutput('incoming.mt')),
                                                        column(2, uiOutput('incoming.price')),
                                                        column(2, 
                                                               style = column.style,
                                                               actionButton('incoming.process',
                                                                            'Procesar'))
                                               )
                                     ))
                            ),
                   
                   #### OP ----
                   tabPanel('OP',
                            navlistPanel(
                              widths = c(2, 10),
                              ## __ New OP ----
                              tabPanel('Nuevo',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(1, uiOutput('po.id')),
                                                          column(2, uiOutput('po.date')),
                                                          column(2, uiOutput('po.contractor')),
                                                          column(2, uiOutput('po.garment')),
                                                          column(2, uiOutput('po.num.garment')),
                                                          column(2, numericInput('po.labor.cost',
                                                                                 'Mano de obra (S/.)',
                                                                                 0)),
                                                          column(1, style = column.style,
                                                                 actionButton('po.process',
                                                                                 'Procesar'))
                                                          )
                                                 ),
                                       actionButton('po.add.input',
                                                    '+ Insumo'),
                                       actionButton('po.check.button',
                                                    'Revisar OP'),
                                       tableOutput('po.check'),
                                       tags$div(id = 'inputListpo')
                              ),
                              
                              ## __ Hand materials ----
                              tabPanel('Entregas',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(2, uiOutput('po.hand.date')),
                                                          column(2, uiOutput('po.hand.id')),
                                                          column(2, uiOutput('po.hand.fabric')),
                                                          column(2, uiOutput('po.hand.quant')),
                                                          column(2, 
                                                                 style = column.style,
                                                                 actionButton('po.hand.process',
                                                                              'Procesar')))),
                                       dataTableOutput('po.hand.input')),
                              
                              ## __ Receive garments ----
                              tabPanel('Recibos',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(2, uiOutput('po.receive.id')),
                                                          column(2, textInput('po.receive.id1',
                                                                              'ID')),
                                                          column(2, uiOutput('po.receive.date')),
                                                          column(2, uiOutput('po.receive.quant')),
                                                          column(2, 
                                                                 style = column.style,
                                                                 actionButton('po.receive.process',
                                                                              'Procesar')),
                                                          column(2, 
                                                                 style = column.style,
                                                                 actionButton('po.receive.complete',
                                                                              'Completo/Incompleto')))),
                                       dataTableOutput('po.receive.output')),
                              
                              ## __ Cut garments ----
                              tabPanel('Corte',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(2, uiOutput('po.cuts.id')),
                                                          column(2, uiOutput('po.cuts.quant')),
                                                          column(2, 
                                                                 style = column.style,
                                                                 actionButton('po.cuts.process',
                                                                              'Procesar')))),
                                       dataTableOutput('po.cuts.output')),
                              
                              ## __ Info OP ----
                              tabPanel('Info',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(2, uiOutput('po.info.id')),
                                                          column(2, 
                                                                 style = column.style,
                                                                 actionButton('po.info.download',
                                                                              'Descargar')),
                                                          column(2, passwordInput('po.info.password',
                                                                                  'Clave')),
                                                          column(2,
                                                                 style = column.style,
                                                                 actionButton('po.info.delete',
                                                                              'Eliminar')))),
                                       h2('Info general'),
                                       dataTableOutput('po.info.general'),
                                       h2('Materiales: '),
                                       dataTableOutput('po.info.materials'),
                                       h2('Prendas: '),
                                       dataTableOutput('po.info.garments'),
                                       h2('Recibos: '),
                                       dataTableOutput('po.info.garments.flow')
                                       )
                              )
                            ),
                   
                   #### Ajustes ----
                   tabPanel('Ajustes',
                            navlistPanel(
                              widths = c(2, 10),
                              ## __ Wild card ----
                              tabPanel('Regularización',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(2, uiOutput('adjustments.date')),
                                                          column(2, selectizeInput('adjustments.operation.type',
                                                                                   'Tipo de ajuste: ',
                                                                                   choices = c('Suma',
                                                                                               'Resta'))),
                                                          column(2, uiOutput('adjustments.fabric')),
                                                          column(2, uiOutput('adjustments.kg')),
                                                          column(2, textInput('adjustments.detail',
                                                                              'Detalle')),
                                                          column(2,
                                                                 style = column.style,
                                                                 actionButton('adjustments.process',
                                                                              'Procesar'))))
                                       ),
                              
                              ## __ Samples ----
                              tabPanel('Muestras',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(2, uiOutput('outgoing.samples.date')),
                                                          column(2, uiOutput('outgoing.samples.contractor')),
                                                          column(2, textInput('outgoing.samples.detail',
                                                                              'Detalle')),
                                                          column(2, 
                                                                 style = column.style,
                                                                 actionButton('outgoing.samples.process',
                                                                              'Procesar')))),
                                       actionButton('outgoing.samples.input',
                                                    '+ Insumo'),
                                       actionButton('outgoing.samples.check',
                                                    'Revisar muestra'),
                                       tableOutput('outgoing.samples.check'),
                                       tags$div(id = 'inputListoutgoing')
                              ),
                              
                              ## __ Direct modifications ----
                              navbarMenu('Modifiación Sistema',
                                       tabPanel('Insumos',
                                                wellPanel(style = wellPanel.style,
                                                          fluidRow(column(2, passwordInput('incoming.modify.password',
                                                                                           'Clave')),
                                                                   column(2, 
                                                                          style = column.style,
                                                                          actionButton('incoming.modify.process',
                                                                                       'Procesar')))),
                                                rHandsontableOutput('incoming.modify.hot.tbl')),
                                       
                                       tabPanel('OP-Recibos',
                                                wellPanel(style = wellPanel.style,
                                                          fluidRow(column(2,  passwordInput('po.received.modify.password',
                                                                                            'Clave')),
                                                                   column(2,
                                                                          style = column.style,
                                                                          actionButton('po.received.modify.process',
                                                                                       'Procesar')))),
                                                rHandsontableOutput('po.received.modify.hot.tbl')
                                                )
                              )
                            )),
                   
                   #### Tables ----
                   tabPanel('Tablas',
                            navlistPanel(
                              widths = c(2, 10),
                              tabPanel('Inventario',
                                       DT::dataTableOutput('inv')),
                              tabPanel('Costo prendas',
                                       DT::dataTableOutput('pocosts'), 
                                       plotOutput('pocostsplot')),
                              tabPanel('Movimientos',
                                       dataTableOutput('movements')),
                              tabPanel('Prendas',
                                       dataTableOutput('garments.flow')))
                            ),
                   
                   #### Add categories ----
                   tabPanel('Bases',
                            navlistPanel(
                              widths = c(2, 10),
                              tabPanel('Telas',
                                       wellPanel(style = wellPanel.style,
                                                 fluidRow(column(6,
                                                                 textInput('new.type.fabric',
                                                                           'Tipo')),
                                                          column(2,
                                                                 style = column.style,
                                                                 actionButton('new.type.fabric.process',
                                                                              'Agregar'))),
                                                 fluidRow(column(3,
                                                                 uiOutput('new.fabric.sub.type.type')),
                                                          column(3,
                                                                 textInput('new.sub.type.fabric',
                                                                           'Sub tipo')),
                                                          column(2,
                                                                 style = column.style,
                                                                 actionButton('new.sub.type.fabric.process',
                                                                              'Agregar'))),
                                                 fluidRow(column(2,
                                                                 uiOutput('new.fabric.type')),
                                                          column(2,
                                                                 uiOutput('new.fabric.sub.type')),
                                                          column(2,
                                                                 textInput('new.fabric.name1',
                                                                           'Nombre comercial')),
                                                          column(2,
                                                                 textInput('new.fabric.name2',
                                                                           'Nombre bautizado')),
                                                          column(1,
                                                                 style = column.style,
                                                                 actionButton('new.fabric.process',
                                                                              'Agregar')))
                                       )),
                              tabPanel('Prendas',
                                       textInput('add.garment.name',
                                                 'Nombre'),
                                       actionButton('add.garment.process',
                                                    'Agregar')),
                              tabPanel('Proveedores',
                                       textInput('add.provider.name',
                                                 'Nombre'),
                                       actionButton('add.provider.process',
                                                    'Agregar')),
                              tabPanel('Contratistas',
                                       textInput('add.contractor.name',
                                                 'Nombre'),
                                       actionButton('add.contractor.process',
                                                    'Agregar'))
                            ))
                   
                   ))
